name: CI

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust Python version as needed

      - name: Install dependencies
        run: |
          pip install homeassistant
          pip install pytest

      - name: Run pytest
        run: pytest

# Optionally, you can add more jobs for other tasks (e.g., linting, code formatting) here.
